name: CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    uses: znamlab/org-workflow-template/.github/workflows/python-uv-ci.yml@v1
    secrets: inherit